coverage:
  status:
    project:
      default:
        informational: true
        target: 40%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
    patch:
      default:
        informational: true
  ignore:
    - "src/components"  # ignore folders and all its contents
    - "src/container"  # ignore folders and all its contents